name: tg_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.0
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  shared_preferences: ^2.1.2
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: 90171aa7692bb07781ec21f98c41e66d91f8cb9d

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
    # Add assets from the images directory to the application.
    # - assets/images/
